baseURL: https://YOUR_GITHUB_USERNAME.github.io/
locale: zh-cn
defaultContentLanguage: zh-cn
title: Jace
theme: "PaperMod"

params:
    homeInfoParams:
        Title: Jace's Notes 👋
        Content: 用 Logseq 记录的思考与知识

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/YOUR_GITHUB_USERNAME"
        - name: "rss"
          url: "/index.xml"
    ShowReadingTime: true
    ShowCodeCopyButtons: true
    author: "Jace"

social:
  facebook_admin: ""

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: search
          name: Search
          url: /search/
          weight: 20
        - identifier: archive
          name: Archive
          url: /archives/
          weight: 20